Restructure
xynga/web-services pull request #18
Opened 2018-06-14 14:56 UTC by jaronson13

- restructure web services
- fix tslint errors/warnings

2018-06-14 16:57 UTC, timjklein36 requested changes
e2e tests failed

2018-06-14 17:27 UTC, jaronson13 commented
hmmm i'll take a look

2018-06-27 14:01 UTC, jaronson13 commented
@timjklein36 I commented out the file upload e2e test which is still giving a 500 error. It's an issue with the api gateway, not the actual web-service. The other e2e tests work though.

 Since we are past the tech debt sprint, I want to merge these changes and then publish the new web-service package. I'll put in a story for the next tech sprint to fix the api gateway response.

2018-06-27 15:59 UTC, timjklein36 approved these changes

2018-06-27 16:48 UTC, merged